name: PipelineWorkflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Azure Pipeline
    runs-on: windows-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/sagarbakshi/Azure%20Devops
          azure-pipeline-name: "sagar-bakshi.pipelines-dotnet-core"
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
